In [1]:
import pandas as pd

## Data Concatenation

### Stacking dataframes on top of each other (rows) or side by side (columns)

In [ ]:
# data ko saath-saath chipka de, ya fir ek k niche ek jod de

In [2]:
df1 = pd.DataFrame({
    'id' : [1, 2, 3],
    'name' : ['Adam', 'Biman', 'Charlie']
})

df2 = pd.DataFrame({
    'id' : [ 4, 5, 6],
    'name' : ['Dora', "Nora", "Lora"]
})

In [4]:
# STACKING DATA ON TOP OF EACH OTHER

pd.concat([df1, df2])     # row-wise concat, here the old index is preserved


pd.concat([df1, df2], ignore_index = True)     # if we want to change old index/label into new ones

   id     name
0   1     Adam
1   2    Biman
2   3  Charlie
3   4     Dora
4   5     Nora
5   6     Lora

In [5]:
# will be stacked in the form of wide table

pd.concat([df1, df2], axis = 1)    # column wise concat
                                   # jo 2nd table hai vo add ho jaygi 1st main as a form of new columns

   id     name  id  name
0   1     Adam   4  Dora
1   2    Biman   5  Nora
2   3  Charlie   6  Lora